### ISSUE TITLE
#defaultMapId has height of 100vh

### ISSUE THREAD

**Issue by RobertCordes** [LarsWiegers/laravel-maps#7]
When using the blade components there is some CSS making the map take up the entire height of the viewport. I have placed the following bit of CSS in my app.css:

```css
#defaultMapId {
    height: 100% !important;
}
```

This obviously fixes the *issue* but I was wondering if there's a better way of configuring this? Maybe (probably) I'm missing something. 🧐

PS: I can already see this package saving me a bunch of time in the future!
